# Generated by Django 3.2.9 on 2021-12-05 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('photo', models.ImageField(upload_to='')),
                ('birth_date', models.DateField()),
                ('pin', models.CharField(blank=True, max_length=4, null=True)),
                ('present_to', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='present_from', to='people.person')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PersonInfoPoint',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('heading', models.TextField()),
                ('info', models.TextField()),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info_points', to='people.person')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
