# Generated by Django 3.2.9 on 2022-12-16 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_auto_20211205_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='birth_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='photo',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
